name: dupfile
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  lottie: ^2.7.0
  file_picker: ^6.1.1
  crypto: ^3.0.3
  sqflite_common_ffi: ^2.3.1
  path_provider: ^2.1.2
  path: ^1.9.0
  url_launcher: ^6.2.5
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
